using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using SmartNursery.DatabaseLayer;

namespace SmartNursery.FormLayer
{
    public partial class TreasuryPaymentForm : DevExpress.XtraEditors.XtraForm
    {
        DataClassesDataContext db = new DataClassesDataContext();
        public TreasuryPaymentForm()
        {
            InitializeComponent();
            //// This line of code is generated by Data Source Configuration Wizard
            //// This line of code is generated by Data Source Configuration Wizard
            //accountsBindingSource.DataSource = new SmartOneImport.DBDataContext().Accounts.Where(o=>o.AccountFlagId == 6 || o.AccountFlagId == 5);
            //repositoryItemSearchLookUpEdit1.DataSource = new SmartOneImport.DBDataContext().DocTypes;
            //repositoryItemSearchLookUpEdit2.DataSource = new SmartOneImport.DBDataContext().Accounts;
        }

        private void searchLookUpEdit1_EditValueChanged(object sender, EventArgs e)
        {
            if(searchLookUpEdit1.EditValue!= null)
            {
                //treasuriesBindingSource.DataSource = new SmartOneImport.DBDataContext().Treasuries.Where(d=>d.AccountId ==Convert.ToInt32(searchLookUpEdit1.EditValue) );
                //gridControl1.DataSource = new SmartOneImport.DBDataContext().TreasuryBalance(Convert.ToInt32(searchLookUpEdit1.EditValue));
                gridControl1.DataSource = db.TreasuryBalance(Convert.ToInt32(searchLookUpEdit1.EditValue));
            }
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            new PaymentsTrejForm().ShowDialog();
            searchLookUpEdit1.EditValue = null;
        }

        private void TreasuryPaymentForm_Load(object sender, EventArgs e)
        {
            searchLookUpEdit1.Properties.DataSource = db.Safes.ToList();
        }
    }
}